---

- hosts: all
  become: true
  pre_tasks:

   - name: update repository index (CentOS)
     tags: always
     yum:
       name: "*"
       state: latest
     changed_when: false
     when: ansible_distribution == "CentOS"

   - name: install updates (Ubuntu)
     tags: always
     apt:
       update_cache: yes
     changed_when: false
     when: ansible_distribution == "Ubuntu"

- hosts: all
  become: true
  roles:
    -  base

- hosts: workstation
  become: true
  roles:
    -  workstation

- hosts: web_servers
  become: true
  roles:
    -  web_servers

- hosts: db_servers
  become: true
  roles:
    -  db_servers

- hosts: file_servers
  become: true
  roles:
    -  file_servers
